#!/bin/bash
# Definition des alias raccourcis
alias cdt='cd ~/test/'
alias cdpconf='cd ~/.config_personal'

# Definition des alias de compilation
alias gccf="gcc -Wall -Wextra -Werror"
alias g++f="g++ -Wall -Wextra -Werror"

# Definition des alias
alias purgevim="rm -f $HOME/.config/nvim/tmp/*"

# Definition des alias git
alias gst="git status"

# Replace ls with exa
exa $HOME >/dev/null 2>&1
if [[ $? == 0 ]]; then
    unalias ls
    unalias ll
    unalias la
    unalias lah
    unalias lh
    alias ls=exa
    alias ll="ls -l --group --git --group-directories-first"
    alias la="ll -a"
    alias lg="ll --grid"
    alias lt="ll --tree"
fi

which nvim 2>&1 > /dev/null
if [[ $? == 0 ]]; then
    alias vim=nvim
fi

# School only aliases
if [[ -n $C_SCHOOL ]]; then
    # misc
    alias auteur="echo '$USER' > auteur"
    alias libft="cp -r $LIB .; rm -rf libft/.git ; rm -f libft/.gitignore"

    # cd alias
    alias cdc='cd ~/Rendu'
    alias cdl='cd $LIB'
    alias cds='cd ~/scripts'

    # compil alias
    alias gccl="gcc -I $LIB/includes -L $LIB -lft"
    alias gcclf="gcc -Wall -Wextra -Werror -I $LIB/includes -L $LIB -lft"
fi

# Home only alias
if [[ "$USER" == "arigowin" ]]; then
    # update
    alias update='sudo apt-get update'
    alias upgrade='sudo apt-get dist-upgrade'
    alias dupgrade='update && sudo apt-get dist-upgrade'

    # install
    alias install='sudo apt-get install'

    # gcc -> clang
    alias gcc='clang'
fi


